# change the followings to match your GitHub username and repo name
baseurl: "/me" # the name of your GitHub repo
url: "https://skullition.dev" # the url of your github pages

# site information used in page title, meta data etc.
title: "Skullition"
description: A page about me, Skullition.

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Skullition
author-bio: false
author-image: 279.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Bitcoin
  permalink: bitcoin
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: https://github.com/Skullition
linkedin: false
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Hello! :)"
footer-msg-link: https://github.com/skullition

# Google Analytics
google-analytics: #G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
